---
title: "`r params$file.output.list$run_id`"
author: ""
date: "`r paste0('Output on ',format(Sys.time(), '%m-%d-%Y'))`"
output: html_document
params:
  file.output.list: file.output.list
  predictMapType: predictMapType
  GeoLines: GeoLines
  plotShape: plotShape
  dmapfinal: dmapfinal
  plots: plots
  k: k
  existGeoLines: existGeoLines
  Rshiny: Rshiny
  input: input
  predictionTitleSize: predictionTitleSize
  scenario_name: scenario_name
  scenario_map_list: scenario_map_list
  master_map_list: master_map_list
  predictionLegendSize: predictionLegendSize
  mapunits.list: mapunits.list
  predictionLegendBackground: predictionLegendBackground
  break1: break1
  Mcolors: Mcolors
  enable_plotlyMaps: enable_plotlyMaps
  output_map_type: output_map_type
  lineWidth: lineWidth
  lon_limit: lon_limit
  lat_limit: lat_limit
  nlty: nlty
  nlwd: nlwd
  CRStext: CRStext
  mapdataname: mapdataname
  predictionMapColors: predictionMapColors
  add_plotlyVars: add_plotlyVars
  mapScenarios: mapScenarios
  predictionMapBackground: predictionMapBackground
  LineShapeGeo: LineShapeGeo
  mapvarname: mapvarname
  predictionClassRounding: predictionClassRounding
  commonvar: commonvar
  map_years: map_years
  map_seasons: map_seasons
  mapsPerPage: mapsPerPage
  mapPageGroupBy: mapPageGroupBy
  aggFuncs: aggFuncs
  path_predictMapsChild: path_predictMapsChild
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE)
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE,fig.width=8, fig.height=8}
#unpack params
predictMapType<-params$predictMapType
GeoLines<-params$GeoLines
plotShape<-params$plotShape
dmapfinal<-params$dmapfinal
plots<-params$plots
k<-params$k
existGeoLines<-params$existGeoLines
Rshiny<-params$Rshiny
input<-params$input
predictionTitleSize<-params$predictionTitleSize
scenario_name<-params$scenario_name
scenario_map_list<-params$scenario_map_list
master_map_list<-params$master_map_list
predictionLegendSize<-params$predictionLegendSize
mapunits.list<-params$mapunits.list
predictionLegendBackground<-params$predictionLegendBackground
break1<-params$break1
Mcolors<-params$Mcolors
enable_plotlyMaps<-params$enable_plotlyMaps
output_map_type<-params$output_map_type
lineWidth<-params$lineWidth
lon_limit<-params$lon_limit
lat_limit<-params$lat_limit
nlty<-params$nlty
nlwd<-params$nlwd
CRStext<-params$CRStext
mapdataname<-params$mapdataname
predictionMapColors<-params$predictionMapColors
add_plotlyVars<-params$add_plotlyVars
commonvar<-params$commonvar
mapScenarios<-params$mapScenarios
predictionMapBackground<-params$predictionMapBackground
LineShapeGeo<-params$LineShapeGeo
mapvarname<-params$mapvarname
predictionClassRounding<-params$predictionClassRounding
map_years<-params$map_years
map_seasons<-params$map_seasons
mapsPerPage<-params$mapsPerPage
mapPageGroupBy<-params$mapPageGroupBy
aggFuncs<-params$aggFuncs
path_predictMapsChild<-params$path_predictMapsChild
    
##########################
##########################
#setup for dynamic mapping
##########################
##########################


print(plots)



##########################
##########################
#end dynamic setup
##########################
##########################

#run mapLoopStr
map_loop.list<-mapLoopStr(file.output.list,predictMapType,GeoLines,
                     plotShape,dmapfinal,plots,k,
                     existGeoLines,Rshiny,input,
                     predictionTitleSize,scenario_name,scenario_map_list,
                     master_map_list,predictionLegendSize,mapunits.list,predictionLegendBackground,
                     break1,Mcolors,
                     enable_plotlyMaps,output_map_type,
                     lineWidth,lon_limit,lat_limit,nlty,nlwd,CRStext,
                     mapdataname,predictionMapColors,add_plotlyVars,
                     mapScenarios,predictionMapBackground,LineShapeGeo,
                     mapvarname,predictionClassRounding,
                     commonvar,
                     map_years,map_seasons,mapsPerPage,mapPageGroupBy,aggFuncs)


unPackList(lists = list(map_loop.list = map_loop.list),
                     parentObj = list(NA))

rmd <- sapply(
  1:(length(unique(plots$plotKey))),
  function(i) {
    knitr::knit_expand(path_predictMapsChild, i = i)
  }
)
rmd <- paste(rmd, collapse = "\n")

```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}

rendered <- knitr::knit(text = rmd, quiet = TRUE)
cat("\n \n")
cat(rendered, sep = "\n")


```

